name: Serverless Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - 'serverless-availability-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: serverless-availability-api

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: serverless-availability-api/package-lock.json

    - run: npm ci

    - name: serverless deploy
      uses: tegud/serverless-github-action@1.52.0
      with:
        command: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
