name: Serverless deploy Service

env:
  WORKING_DIRECTORY: 'serverless-availability-api'
  REPOSITORY: 'TopVakantiehuizen/serverless-functions'

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Environment stage'
        required: true
        default: 'dev'
  pull_request:
    types: [opened]
#     paths: 
#       - '$WORKING_DIRECTORY/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # can be a dynamic path, so we can reuse this workflow for multiple serverless functions
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Notify about starting this deployment 
        uses: hasura/comment-progress@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.REPOSITORY }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: 'Starting deployment of this pull request.'

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'serverless-availability-api/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Deploy service to AWS
        run: |
          npx serverless config credentials \
          --provider aws \
          --key ${{ secrets.AWS_ACCESS_KEY_ID }} \
          --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          
          npx serverless deploy \
          --stage ${{ github.event.inputs.stage }}

      - name: Notify about the result of this deployment 
        uses: hasura/comment-progress@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ env.REPOSITORY }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: 'Deployment of a preview for this pull request was successful.'
          append: true
