name: Serverless remove Service

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Environment stage'
        required: true
        default: 'dev'
#  push:
#    branches: [ "main" ]
#    paths:
#      - 'serverless-availability-api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # can be a dynamic path, so we can reuse this workflow for multiple serverless functions
        working-directory: serverless-availability-api

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: serverless-availability-api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Remove service from AWS
        run: |
          npx serverless config credentials \
          --provider aws \
          --key ${{ secrets.AWS_ACCESS_KEY_ID }} \
          --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          
          npx serverless remove \
          --stage ${{ github.event.inputs.stage }}
