name: Serverless Deploy

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Environment stage'
        required: true
        default: 'dev'
  push:
    branches: [ "main" ]
    paths:
      - 'serverless-availability-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: serverless-availability-api/package-lock.json

    #- run: cd serverless-availability-api && npm ci

    - run: |
        cd serverless-availability-api && npm ci \
        && serverless config credentials \
        --provider aws \
        --key ${{ secrets.AWS_ACCESS_KEY_ID }} \
        --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        && serverless deploy \
        --stage ${{ github.event.inputs.stage }}

    - run: |
        cd serverless-availability-api && \
        serverless deploy \
        --stage ${{ github.event.inputs.stage }}
